services:
 mongo-products:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_product_data:/data/db
    
 mysql-order:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_order_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-inventory:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_inventory_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 product-service:
  depends_on:
    - mongo-products
  image: rafengelen/product-service
  ports:
    - 8080:8080
  links:
    - mongo-products
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-products
   
 inventory-service:
  depends_on:
    - mysql-inventory
  image: rafengelen/inventory-service
  ports:
    - 8082:8082
  links:
    - mysql-inventory
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-inventory
   MYSQL_DB_PORT: 3307

 order-service:
  depends_on:
    - product-service
    - inventory-service
  image: rafengelen/order-service
  ports:
    - 8081:8081
  links:
    - product-service
    - inventory-service
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   INVENTORY_INFO_SERVICE_BASEURL: inventory-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-order
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - product-service
     - order-service
   image: rafengelen/gaatwaay
   ports:
     - 8083:8083
   links:
     - product-service
     - order-service
   environment:
     PRODUCT_SERVICE_BASEURL: product-service:8080
     ORDER_SERVICE_BASEURL: order-service:8081

volumes:
 mongodb_product_data:
 mysql_inventory_data:
 mysql_order_data: